name: new_music
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

  provider: ^6.0.5
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.2.8+4
  flutter_localizations:
      sdk: flutter
  localization:
  intl: any
  audioplayers: ^4.1.0
  just_audio: ^0.9.33
  audio_video_progress_bar: ^1.0.1
  youtube_explode_dart: ^1.12.4
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  youtube_player_flutter: ^8.1.2
  video_player: ^2.6.1
  connectivity_plus: ^4.0.1








dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  generate: true

  uses-material-design: true


  fonts:
    - family: My_Font
      fonts:
        - asset: assets/fonts/CherryCreamSoda-Regular.ttf
        - asset: assets/fonts/CherryCreamSoda-Regular.ttf
          style: italic
    - family: My_Font2
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf
        - asset: assets/fonts/LilitaOne-Regular.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/
    - assets/image/
    - assets/icon/







